feat: add publisher program to sync cli
pyth-network/program-admin pull request #44
Opened 2024-09-05 12:44 UTC by ali-bahjati

2024-09-06 15:07 UTC, Riateche requested changes

2024-09-06 15:07 UTC, Riateche commented on program_admin/publisher_program_instructions.py
> +            AccountMeta(pubkey=config_account, is_signer=False, is_writable=True),
config doesn't need to be writable here.

2024-09-09 11:59 UTC, ayazabbas commented on program_admin/__init__.py
> +    async def account_exists(self, key: PublicKey) -> bool:
There is already an `account_exists` function in util.py (it's being imported and used already in this file too)

2024-09-09 12:24 UTC, ayazabbas approved these changes

2024-09-09 12:50 UTC, ali-bahjati commented on program_admin/__init__.py
> +from program_admin.publisher_program_instructions import (
actually it seems that the formatter in pre-commit (black i assume) is breaking them apart. idk why but i can't join them.

2024-09-09 12:53 UTC, Riateche approved these changes

2024-09-09 13:16 UTC, merged